on:
  push:
    branches:
      - "main"
  pull_request:


name: Testing

jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - "1.81"
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.1
        name: Cargo Cache
        with:
          command: cache
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        name: Install Rust toolchain
        with:
          command: install-rustup
          toolchain: ${{ matrix.rust }}
          profile: minimal
          default: true
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        name: Install nextest
        with:
          command: cargo install
          args: cargo-nextest

      - name: Install Dart toolchain
        uses: dart-lang/setup-dart@v1

      - name: Run cargo nextest
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        run: cargo nextest run --all


  lints:
    name: Lints
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - "1.81"
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions/checkout@v3
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.1
        name: Cargo Cache
        with:
          command: cache
      - uses: FrancisRussell/ferrous-actions@v0.1.0-beta.2
        name: Install Rust toolchain
        with:
          command: install-rustup
          toolchain: ${{ matrix.rust }}
          profile: minimal
          components: clippy rustfmt
          default: true
          
      - name: Format
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        run: cargo fmt --all -- --check

      - name: Clippy
        continue-on-error: ${{ matrix.rust == 'nightly' }}
        run: cargo clippy -- -D warnings
